name: MOOV
description: A game changing app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  material_segmented_control: ^2.1.0
  cloud_firestore: ^0.13.0+1
#  cloud_firestore: ^0.14.2
  firebase_storage: ^3.1.0+1
#  firebase_storage: ^5.0.0
  image_picker: ^0.6.7+4
  firebase_messaging: ^6.0.16
#  firebase_core: ^0.5.1
  firebase_core: ^0.4.4
  shared_preferences: ^0.5.0
  date_range_picker: ^1.0.6
  image_cropper: ^1.2.3
  datetime_picker_formfield: ^1.0.0
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.18.0
  geolocator: ^5.3.2+2
  image: ^2.1.14
  firebase_auth: ^0.16.0
#  firebase_auth: ^0.18.2
  google_sign_in: ^4.4.4
  permission_handler: ^5.0.0
  contacts_service: ^0.3.10
  flutter_sms: ^2.0.0
  firebase_analytics: ^5.0.6
  flutter_form_builder: ^3.7.2
  duration: ^2.0.0
#  get_it: ^4.0.2
  http:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  path_provider: ^1.3.0
  provider: ^4.3.2
  timeago: ^2.0.17
  share: ^0.6.5+4
  flutter_screenutil: ^4.0.0








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/appicon.png
    - lib/assets/google.png
    - lib/assets/moovheader.png
    - lib/assets/foodbutton1.png
    - lib/assets/motd.jpg
    - lib/assets/bouts.jpg
    - lib/assets/pete!!.jpg
    - lib/assets/filmbutton1.png
    - lib/assets/sportbutton1.png
    - lib/assets/partybutton1.png
    - lib/assets/otherbutton1.png
    - lib/assets/dummyqr.png
    - lib/assets/ndlogo.png
    - lib/assets/kilwins.jpg
    - lib/assets/chens.jpg
    - lib/assets/woman.jpg
    - lib/assets/chinese.png
    - lib/assets/studybutton1.png
    - lib/assets/govbutton1.png
    - lib/assets/massbutton1.png
    - lib/assets/volunteerbutton1.png
    - lib/assets/charitybutton1.png
    - lib/assets/tailgatebutton1.png
    - lib/assets/gamesbutton1.png
    - lib/assets/otherbutton2.png
    - lib/assets/me.jpg
    - lib/assets/friendfinder.png
    - lib/assets/alvin.png
    - lib/assets/food5.png
    - lib/assets/party2.png
    - lib/assets/club2.png
    - lib/assets/bag1.png
    - lib/assets/fg1.png
    - lib/assets/ff.png
    - lib/assets/moovblue.png
    - lib/assets/sendmoov.png
    - lib/assets/launchscreen1.png
    - lib/assets/landingpage.png
    - lib/assets/moovlogo2.png
    - lib/assets/fire.png
    - lib/assets/plate.png
    - lib/assets/dance.png
    - lib/assets/trophy.png
    - lib/assets/trophy2.png
    - lib/assets/verif.png



    # - lib/assets/google1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: assets/Pacifico-Regular.ttf
fonts: 
  - family: Solway
    fonts:
    - asset: lib/assets/fonts/Solway-Regular.ttf
    - asset: lib/assets/fonts/Solway-Bold.ttf
      weight: 700
      style: italic

  - family: OpenSans-Bold
    fonts:
      - asset: lib/assets/fonts/OpenSans-Bold.ttf

    # - family: Solway
    #   fonts:
    #     - asset: lib/fonts/So.ttf
    #     - asset: lib/fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages